name: Github CI Backend
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        
      - name: Run integration and unit tests
        run: npm run test